### ISSUE TITLE
Is a good idea to use lodash sub-packages ?

### ISSUE THREAD

**Issue by danielo515** [xodio/hm-def#10]
Hello,

One of the things introduced on the great PR #8 was some lodash deps. I understand that the intention was to minimize the dependencies introduced by using just two subpackages of lodash instead of the entire lodash.
However, I see this as an anti pattern for 3 main reasons:

1. Lodash is a very spread dependency, and if any of your dependencies includes lodash you will end with the entire lodash library plus your independent packages, just the opposite you want.
1. Independend lodash packages are pretty outdated and they do not have proper documentation
1. Individual packages have been discontinued by lodash author (see https://github.com/lodash/lodash/issues/3565#issuecomment-353970667)

So it may be a better idea to just use lodash.
What do you think ?

**Comment by nkrkv** [comment]
Why did Lodash ever appeared among the dependencies? `cond` and `fromPairs` were initially provided by Ramda.

— _Ramda is not safe, Sanctuary is better, let’s get rid of Ramda in favor of Sanctuary._ That was a good idea for #8 

But Sanctuary misses a few functions from Ramda. They are quite trivial and are re-implemented on the top of `signature.js`:

```js
//    isEmpty :: Foldable f => f a -> Boolean
const isEmpty = xs => xs.length === 0;
//    propEq :: String -> a -> StrMap a -> Boolean
const propEq = prop => val => obj => obj[prop] === val;
//    indexBy :: (StrMap a -> String) -> Array (StrMap a) -> StrMap (StrMap a)
const indexBy = memoize
  (f => S.reduce
    (xs => x => S.insert (f (x)) (x) (xs))
    ({}));
```

The missing `cond` and `fromPairs` look trivial too and IMO it is better to just re-implement them the same way and drop the `lodash.*` dependencies altogether.

PRs are welcome.

**Comment by nkrkv** [comment]
Oh, thanks. For the strictness and definite return value type exception is fine I think.

**Comment by Gipphe** [comment]
My thoughts exactly.

**Comment by davidchambers** [comment]
This signature is misleading:

> ```javascript
> //    isEmpty :: Foldable f => f a -> Boolean
> const isEmpty = xs => xs.length === 0;
> ```

One of the following would be accurate:

```javascript
//    isEmpty :: { length :: Number } -> Boolean
const isEmpty = xs => xs.length === 0;
```

```javascript
//    isEmpty :: Foldable f => f a -> Boolean
const isEmpty = xs => S.size (xs) === 0;
```

```javascript
//    isEmpty :: Monoid a => a -> Boolean
const isEmpty = xs => S.equals (xs) (S.empty (xs.constructor));
```
