### ISSUE TITLE
Support for Record types

### ISSUE THREAD

**Issue by jtormey** [xodio/hm-def#6]
It would be nice if there were a way to add RecordTypes, for example:

```js
const User = $.RecordType({
  id: $.Number,
  first: $.String,
  last: $.String
})

const env = $.env.concat([User])
```

This doesn't work (as far as I can tell) because the Type `name` in the env is `'RECORD'`, so hm-def can't find a User type.

A workaround is to define a `NullaryType`, but to do this I have to provide my own `test` function (can't use the more declarative style like when creating a RecordType).

```js
const R = require('ramda')

const User = $.NullaryType(
  'User',
  'https://github.com/blockchain/blockchain-wallet-v4-frontend#User',
  R.where({
    id: R.is(Number),
    first: R.is(String),
    last: R.is(String)
  })
)

const env = $.env.concat([User])

const def = hmDef.default.create({
  env: env,
  checkTypes: true
})

const getUserName = def(
  'getUserName :: User -> String',
  (user) => user.first + ' ' + user.last
)
```

Do you know if there is a better way to accomplish this?

**Comment by evgenykochetkov** [comment]
Well, we do something like this:
https://github.com/xodio/xod/blob/master/packages/xod-project/src/types.js
https://github.com/xodio/xod/blob/master/packages/xod-func-tools/src/types.js#L91

**Comment by jtormey** [comment]
That's great, thanks! Your approach works perfectly:

```js
const Model = (packageName, docUrl, schema) => (
  $.NullaryType(
    packageName,
    docUrl,
    (a) => $.RecordType(schema).validate(a).isRight
  )
)

const User = Model('User', 'http://example.com#User', {
  id: $.Number,
  first: $.String,
  last: $.String
})

const env = $.env.concat([User])
```
